default:
  plugins:
    - image
    - link
    - code
    - codesample
    - media

alternate:
  selector: textarea.table-editor
  toolbar: styleselect | bold italic | undo redo | table
  plugins:
    - table